basePath: /
definitions:
  model.AuthMe:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  model.BaseResponse:
    properties:
      data: {}
      message:
        example: Message!
        type: string
    type: object
  model.CustomerResponse:
    properties:
      date_birth:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: integer
      identity_file:
        type: string
      legal_name:
        type: string
      nik:
        type: string
      place_birth:
        type: string
      salary:
        type: number
      selfie_file:
        type: string
    type: object
  model.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  model.TenorResponse:
    properties:
      amount:
        type: number
      id:
        type: integer
      month:
        type: integer
    type: object
info:
  contact: {}
  description: This is the API documentation for Kredit Plus backend services.
  title: BE Kredit Plus
  version: "1.0"
paths:
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: Handles user login by verifying credentials and returning authentication
        data.
      parameters:
      - description: Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful login response
          schema:
            $ref: '#/definitions/model.BaseResponse'
        "401":
          description: Unauthorized error response
          schema:
            $ref: '#/definitions/model.BaseResponse'
      summary: Authenticate user login
      tags:
      - auth
  /v1/auth/me:
    get:
      consumes:
      - application/json
      description: Retrieves information about the currently authenticated user.
      produces:
      - application/json
      responses:
        "200":
          description: Successful user info response
          schema:
            allOf:
            - $ref: '#/definitions/model.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.AuthMe'
              type: object
        "401":
          description: Unauthorized error response
          schema:
            $ref: '#/definitions/model.BaseResponse'
      security:
      - AccessToken: []
      summary: Get authenticated user info
      tags:
      - auth
  /v1/customer/information:
    get:
      consumes:
      - application/json
      description: Retrieves information about the customer.
      produces:
      - application/json
      responses:
        "200":
          description: Successful customer information response
          schema:
            allOf:
            - $ref: '#/definitions/model.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.CustomerResponse'
              type: object
        "401":
          description: Unauthorized error response
          schema:
            $ref: '#/definitions/model.BaseResponse'
      security:
      - AccessToken: []
      summary: Get customer information
      tags:
      - customer
  /v1/customer/tenor:
    get:
      consumes:
      - application/json
      description: Retrieves available tenor for the customer.
      produces:
      - application/json
      responses:
        "200":
          description: Successful customer tenor response
          schema:
            allOf:
            - $ref: '#/definitions/model.BaseResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.TenorResponse'
                  type: array
              type: object
        "401":
          description: Unauthorized error response
          schema:
            $ref: '#/definitions/model.BaseResponse'
      security:
      - AccessToken: []
      summary: Get customer tenor
      tags:
      - customer
securityDefinitions:
  AccessToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
